<?php
$z[0]=Array("field","",64,92);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",94,123);
$z[1][4]['name']="typename";
$z[2]=Array("field","",192,220);
$z[2][4]['name']="typeurl";
$z[3]=Array("arclist","\r\n								<li><span>[field:pubdate function=\"MyDate('m-d',@me)\"/]</span>\r\n									<a href=\"[field:arcurl /]\">[field:title /]</a>\r\n								</li>\r\n								",315,520);
$z[3][4]['titlelen']="60";
$z[3][4]['row']="6";

?>