<?php
$z[0]=Array("field","",85,114);
$z[0][4]['name']="typename";
$z[1]=Array("type","\r\n							<span class=\"more\">\r\n								<a href=\"[field:typelink /]\">更多...</a>\r\n							</span>\r\n							",145,274);
$z[2]=Array("arclist","\r\n								<li><span>[field:pubdate function=\"MyDate('m-d',@me)\"/]</span>\r\n									<a href=\"[field:arcurl /]\">[field:title /]</a>\r\n								</li>\r\n								",338,543);
$z[2][4]['titlelen']="60";
$z[2][4]['row']="6";

?>