<a href="javascript:void(0)" target="_blank">
				<img src="[field:picname/]" />
			</a>
			<div style="position: absolute; top: 2px;left: 2px; padding: 5px;color: #000000;text-indent: 2em;overflow: hidden;">
				<h2 style="text-align: center;"><a href="[field:arcurl/]">[field:title/]</a></h2>
				<p style="text-indent: 2em;">
					[field:info/]...
					<a href="[field:arcurl/]">[查看全文]</a>
				</p>
			</div>