<?php
$z[0]=Array("field","",46,73);
$z[0][4]['name']="arcurl";
$z[1]=Array("field","",75,104);
$z[1][4]['name']="typename";
$z[2]=Array("field","",145,173);
$z[2][4]['name']="typeurl";
$z[3]=Array("arclist","\r\n								<li><span>[field:pubdate function=\"MyDate('m-d',@me)\"/]</span>\r\n									<a href=\"[field:arcurl /]\">[field:title /]</a>\r\n								</li>\r\n								",251,456);
$z[3][4]['titlelen']="60";
$z[3][4]['row']="6";

?>