<?php
$z[0]=Array("global","",215,241);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",921,948);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("channel","\r\n						<li>\r\n							<a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a>\r\n						</li>\r\n						",995,1172);
$z[2][4]['type']="son";
$z[2][4]['row']="8";
$z[2][4]['typeid']="1";
$z[3]=Array("mda","",1314,1343);
$z[3][4]['name']="950x90_SSP";

?>